import { useState, useRef} from 'react';
import { StyleSheet, View, TextInput} from 'react-native';
import {StyledButton, StyledButtonBlue, StyledButtonLongBlue, StyledButtonLongRed} from '../components/StyledButton';

const CalculatorScreen = () => {
  const [display, setDisplay] = useState('0');
  const [memory, setMemory] = useState('');

  // triggered when a number is pressed
  const handleNumberPress = (number) => {
    if (display === '0') {
      setDisplay(number);
    } else {
      setDisplay(display + number);
    }
    setMemory(memory + number);
  };

  const handleDelete = () => {
    if(memory.length <= 1){
      handleClearPress();
    } else {
      var newMem = memory.slice(0, -1);
      setDisplay(newMem);
      setMemory(newMem);
    }
  };

  // triggered when an operator is pressed
  const handleOperatorPress = (operator) => {
    if (operator === 'x'){
      //this is only necessary if the picture of the calculator is accurate in the rubric
      operator = '*';
    }
    setMemory(memory + operator);
    setDisplay(memory + operator);
  };

  // triggered when an decimal is pressed
  const handleDecimalPress = (decimal) => {
    var mathWithTrailDec = memory + decimal + '0';
    var mathWithLeadDec = memory + '0' + decimal + '0';
    if (isValidMath(mathWithTrailDec)){
      setMemory(memory + decimal);
      setDisplay(memory + decimal);
    }
    else if (isValidMath(mathWithLeadDec)){
      setMemory(memory + '0' + decimal);
      setDisplay(memory + '0' + decimal);
    } 
  };

  // triggered when the equal sign is pressed
  const handleEqualPress = () => {
    if (isValidMath(memory)){
      const res = eval(memory);
      if (res === Infinity){
        setDisplay('Error');
        setMemory('Error');
      } else {
        setDisplay(res + '');
        setMemory(res + '');
      }
    } else {
      setDisplay('Error');
      setMemory('Error');
    }
  };

  // triggered when the clear button is pressed
  const handleClearPress = () => {
    setDisplay('0');
    setMemory('');
  };

  /* ========== CREDIT ==========
   * Regular expressions and logic in isValidMath and isValidNumber generated by ChatGPT to aid with decimal handling 
  */

  const isValidMath = (s) => {
    // define the regular expression pattern
    //regular expression for valid math equation without trailing decimal 
    //const pattern = /^\s*\d+(\.\d+)?\s*([+\-*/]\s*\d+(\.\d+)?\s*)*$/;

    //modified regular expression to account for accidental decimal at the end of an expression
    //e.g. 6.2 + 5. would be the same as 6.2 + 5 which evaluates to 11.2 
    const pattern = /^\s*\d+(\.\d+)?\s*([+\-*/]\s*\d+(\.\d+)?\s*)*\.?\s*$/;
  
    // match the string against the pattern
    const match = s.match(pattern);
  
    // return true if the string matches the pattern, false otherwise
    return Boolean(match);
  }

  /* const formatDisplay = (display) => {
    //before every press, check that the display is only displaying a certain number of characters. If it is displaying more than 12 shrink the size of the font to allow for 3 more numbers. Only a maximum of 15 characters are allowed on screen at a time.
    const inputRef = useRef(null);

    // Modify the style of the TextInput using setNativeProps
    if (display.length === 12) {
      inputRef.current.setNativeProps({
        style: { fontSize: 30 },
      });
    } else if (display.length > 15){
      return;
    }
    return (
      <TextInput
        ref={inputRef}
        style={styles.input}
        value={display}
        editable={false}
        testID='calculator-input'
      />
    );
  }; */

  return (
    <View style={styles.subContainer} testID='calculator-screen'>
      <TextInput style={styles.result} value={display} editable={false} testID='calculator-input' />
      <View style={styles.buttonWrapper}>
        <View style={styles.row}>
          <StyledButton text='7' handler={handleNumberPress} />
          <StyledButton text='8' handler={handleNumberPress} />
          <StyledButton text='9' handler={handleNumberPress} />
          <StyledButtonBlue text='DEL' handler={handleDelete}/>
        </View>
        <View style={styles.row}>
          <StyledButton text='4' handler={handleNumberPress} />
          <StyledButton text='5' handler={handleNumberPress} />
          <StyledButton text='6' handler={handleNumberPress} />
          <StyledButton text='+' handler={handleOperatorPress} />
        </View>
        <View style={styles.row}>
          <StyledButton text='1' handler={handleNumberPress} />
          <StyledButton text='2' handler={handleNumberPress} />
          <StyledButton text='3' handler={handleNumberPress} />
          <StyledButton text='-' handler={handleOperatorPress} />
        </View>
        <View style={styles.row}>
          <StyledButton text='.' handler={handleDecimalPress} />
          <StyledButton text='0' handler={handleNumberPress} />
          <StyledButton text='/' handler={handleOperatorPress} />
          <StyledButton text='x' handler={handleOperatorPress} />
        </View>
        <View style={styles.row}>
          <StyledButtonLongBlue text='RESET' handler={handleClearPress} />
          <StyledButtonLongRed text='=' handler={handleEqualPress} />
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  subContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonWrapper: {
    backgroundColor: 'hsl(223, 31%, 20%)', //Very dark desaturated blue
    borderRadius: 5,
    padding: 20,
    paddingBottom: 10,
    width: '80%',
  },
  result: {
    width: '80%',
    height: 80,
    fontSize: 40,
    color: 'hsl(0, 0%, 100%)', //White
    textAlign: 'right',
    fontFamily: 'LeagueSpartan-Bold',
    //fontWeight: 'bold',
    marginBottom: 20,
    backgroundColor: 'hsl(224, 36%, 15%)', //Very dark desaturated blue
    borderRadius: 5,
    padding: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
});

export default CalculatorScreen;
